#packmode expert

// The Ultimate Singularity
recipes.remove(<extendedcrafting:singularity_ultimate>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER", <extendedcrafting:singularity_ultimate> * 1, [[<avaritia:singularity:0>, <avaritia:singularity:1>, <avaritia:singularity:2>, <avaritia:singularity:3>, <avaritia:singularity:4>, <avaritia:singularity:5>, <avaritia:singularity:6>, <avaritia:singularity:7>, <avaritia:singularity:8>], [<avaritia:singularity:9>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:singularity:10>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <extendedcrafting:singularity:50>],[<extendedcrafting:singularity:19>, <avaritia:resource:6>, <avaritia:neutron_collector>, <avaritia:singularity:12>, <avaritia:neutron_collector>, <avaritia:singularity:11>, <avaritia:neutron_collector>, <avaritia:resource:6>, <extendedcrafting:singularity:64>],[<extendedcrafting:singularity:18>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:singularity:13>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <extendedcrafting:singularity:65>],[<extendedcrafting:singularity:20>, <eternalsingularity:combined_singularity:5>, <eternalsingularity:combined_singularity:4>, <eternalsingularity:combined_singularity:7>, <avaritia:singularity:14>, <eternalsingularity:combined_singularity:11>, <eternalsingularity:combined_singularity:15>, <eternalsingularity:combined_singularity:2>, <extendedcrafting:singularity:66>],[<extendedcrafting:singularity:21>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity:48>, <eternalsingularity:combined_singularity:3>, <eternalsingularity:eternal_singularity>, <extendedcrafting:singularity:4>, <extendedcrafting:singularity:5>, <extendedcrafting:singularity:16>, <extendedcrafting:singularity:32>],[<extendedcrafting:singularity:22>, <extendedcrafting:singularity:0>, <extendedcrafting:singularity:3>, <eternalsingularity:combined_singularity:10>, <eternalsingularity:combined_singularity:6>, <eternalsingularity:combined_singularity:14>, <extendedcrafting:singularity:6>, <extendedcrafting:singularity:7>, <extendedcrafting:singularity:24>],[<extendedcrafting:singularity:23>, <extendedcrafting:singularity:2>, <eternalsingularity:combined_singularity:0>, <extendedcrafting:singularity:35>, <eternalsingularity:combined_singularity:8>, <extendedcrafting:singularity:34>, <eternalsingularity:combined_singularity:13>, <extendedcrafting:singularity:49>, <extendedcrafting:singularity:33>],[<extendedcrafting:singularity:25>, <eternalsingularity:combined_singularity:1>, <extendedcrafting:singularity:27>, <extendedcrafting:singularity:26>, <extendedcrafting:singularity:29>, <extendedcrafting:singularity:28>, <extendedcrafting:singularity:30>, <eternalsingularity:combined_singularity:12>, <extendedcrafting:singularity:31>]]);






recipes.remove(<danknull:dank_null_0>);
recipes.remove(<danknull:dank_null_1>);
recipes.remove(<danknull:dank_null_2>);
recipes.remove(<danknull:dank_null_3>);
recipes.remove(<danknull:dank_null_4>);
recipes.remove(<danknull:dank_null_5>);


recipes.remove(<danknull:dank_null_panel_0>);
recipes.remove(<danknull:dank_null_panel_1>);
recipes.remove(<danknull:dank_null_panel_2>);
recipes.remove(<danknull:dank_null_panel_3>);
recipes.remove(<danknull:dank_null_panel_4>);
recipes.remove(<danknull:dank_null_panel_5>);
















































































































































































































